
Partial Class add_budget
    Inherits basePage

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        If Not Page.IsPostBack Then
            TotalRevenue_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            RETAIL_TESPIncome_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            OtherRevenue_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            CostofGoodSold_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            GrossProfit_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            GrossProfit_percent_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            MarginAdjustments_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Shipping_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            StockLossandObsolescence_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            InventoryAdjustment_stock_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            InventoryAdjustment_damage_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            StockLoss_Provision_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            StockObsolescence_Provision_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            GWP_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            GWPs_Corporate_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            GWPs_Transferred_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            SellingCosts_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Creditcardscommission_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            LabellingMaterial_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            OtherIncome_COSHFunding_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            OtherIncomeSupplier_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            AdjustedGrossMargin_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            SupplyChainCosts_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            TotalStoreExpenses_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            StoreLabourCosts_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            GrossPay_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            TemporaryStaffCosts_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Allowance_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Overtime_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Licensefee_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Bonuses_Incentives_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            BootsBrandncentives_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            SuppliersIncentive_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            ProvidentFund_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            PensionCosts_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            SocialSecurityFund_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Uniforms_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            EmployeeWelfare_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            OtherBenefitsEmployee_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            StorePropertyCosts_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            PropertyRental_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            PropertyServices_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            PropertyFacility_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Propertytaxes_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Facialtaxes_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            PropertyInsurance_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Signboard_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Discount_Rent_Services_Facility_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            GPCommission_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            AmortizationofLeaseRight_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Depreciation_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            DepreciationofShortLeaseBuilding_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            DepreciationofComputerHardware_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            DepreciationofFixturesFittings_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            DepreciationofComputerSoftware_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            DepreciationofOfficeEquipment_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            OtherStoreCosts_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            ServiceChargesandOtherFees_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            BankCharges_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            CashCollectionCharge_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Cleaning_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            SecurityGuards_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Carriage_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            LicenceFees_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            OtherServicesCharge_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            OtherFees_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Utilities_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Water_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Gas_Electric_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            AirCond_Addition_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            RepairandMaintenance_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            RMOther_Fix_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            RMOther_Unplan_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            RMComputer_Fix_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            RMComputer_Unplan_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            ProfessionalFee_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            MarketingResearch_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            OtherFee_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Equipment_MaterailandSupplies_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            PrintingandStationery_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            SuppliesExpenses_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Equipment_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Shopfitting_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            PackagingandOtherMaterial_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            BusinessTravelExpenses_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            CarParkingandOthers_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Travel_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Accomodation_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            MealandEntertainment_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Insurance_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            AllRiskInsurance_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            HealthandLifeInsurance_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            PenaltyandTaxation_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Taxation_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Penalty_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            OtherRelatedStaffCost_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            StaffConferenceandTraining_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Training_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Communication_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            TelephoneCalls_Faxes_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            PostageandCourier_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            OtherExpenses_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Sample_Tester_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            PreopeningCosts_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            LossonClaim_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            CashOvertage_Shortagefromsales_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            MiscellenousandOther_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            StoreTradingProfit__Loss_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            TradingProfit__Loss_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            StoreControllableCostsforBSC_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            StoreLabourCost_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            Utillity_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
            RepairMaintenance_Txt.Attributes.Add("onkeypress", "return Numbers(event);")
        End If
    End Sub

    Protected Sub SaveBt_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles SaveBt.Click

    End Sub
End Class
