
Partial Class lfl_mtd_compare
    Inherits basePage

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        If Not Page.IsPostBack Then
            Panel1.Visible = False
            ddlYear.DataValueField = "mon_year"
            ddlYear.DataTextField = "mon_year"
            ddlYear.DataSource = ClsDB.getMtdYear()
            ddlYear.DataBind()

            ddlMonth.DataValueField = "mon_year"
            ddlMonth.DataTextField = "mon_name"
            ddlMonth.DataSource = ClsDB.getMtdMonth(ddlYear.SelectedValue)
            ddlMonth.DataBind()

            ClsDB.getCurrentcyToDDL(ddlRate)
            ClsDB.getFormatToDDL(ddlFormat)

            Dim white As Drawing.Color = Drawing.Color.FromName(Drawing.Color.FromArgb(149, 179, 215).Name)
            SearchBt.BackColor = white
            Dim x As String = white.ToString

        End If
    End Sub

    Protected Sub ddlYear_TextChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles ddlYear.TextChanged
        ddlMonth.DataValueField = "mon_year"
        ddlMonth.DataTextField = "mon_name"
        ddlMonth.DataSource = ClsDB.getMtdMonth(ddlYear.SelectedValue)
        ddlMonth.DataBind()
    End Sub

    Protected Sub SearchBt_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles SearchBt.Click
        Panel1.Visible = True
        Pftb.Visible = True
        TbCk.Text = 0

        If ddlBy.SelectedIndex = 0 Then
            odsMonth.SelectParameters("years").DefaultValue = ddlYear.SelectedValue
            odsMonth.SelectParameters("mon").DefaultValue = ddlMonth.SelectedValue
            odsMonth.SelectParameters("type").DefaultValue = ddlModel.SelectedValue
            odsMonth.SelectParameters("store_id").DefaultValue = ddlFormat.SelectedValue
            odsMonth.SelectParameters("rate").DefaultValue = ddlRate.SelectedValue
            odsMonth.SelectParameters("growth").DefaultValue = "y"
            DataList2.DataSourceID = odsMonth.ID
        Else
            odsYear.SelectParameters("years").DefaultValue = ddlYear.SelectedValue
            odsYear.SelectParameters("mon").DefaultValue = ddlMonth.SelectedValue
            odsYear.SelectParameters("type").DefaultValue = ddlModel.SelectedValue
            odsYear.SelectParameters("store_id").DefaultValue = ddlFormat.SelectedValue
            odsYear.SelectParameters("rate").DefaultValue = ddlRate.SelectedValue
            odsMonth.SelectParameters("growth").DefaultValue = "n"
            DataList2.DataSourceID = odsYear.ID
        End If


        DataList2.DataBind()
        DataList2.Visible = True
        Pftb.Visible = True
        ClsManage.Script(Page, "settb('b');settb('e');settb('f');settb('g');settb('h');settb('s');settb('aa');")
       

    End Sub

    Protected Sub linkExcel_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles linkExcel.Click
        Try
            Dim sw As New IO.StringWriter()
            Dim htw As New HtmlTextWriter(sw)
            temp_body.RenderControl(htw)

            Dim excelName As String = "MTD_LFL_Report_" + ddlMonth.SelectedValue + ddlYear.SelectedValue
            ClsDB.ExportToExcel(htw.InnerWriter.ToString, excelName)
        Catch ex As Exception

        End Try
    End Sub

    Protected Sub DataList2_ItemDataBound(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.DataListItemEventArgs) Handles DataList2.ItemDataBound
        If e.Item.ItemType = ListItemType.Item Or e.Item.ItemType = ListItemType.AlternatingItem Then
            If e.Item.DataItem("SumTotalRevenue") IsNot DBNull.Value Then
                TbCk.Text = Convert.ToDecimal(TbCk.Text) + 1
                If Not e.Item.DataItem("ptype") = ddlModel.SelectedValue Then

                    CType(e.Item.FindControl("label2"), Label).Text = "<TABLE cellspacing='0' cellpadding='0' class='tball'>" + _
                "<TR style='font-weight:bold;' class='kbg1'><TD align='center'><div style='width:110px'><strong>" + e.Item.DataItem("SumCostCenter").ToString + "</strong></div></TD><TD align='center'><div style='width:65px;'><strong></strong></div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg1'><TD align='center'><div style='width:110px'><strong>" + e.Item.DataItem("ptype").ToString + "</strong></div></TD><TD align='center'><div style='width:65px;'><strong>%Sale</strong></div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='center'><div style='width:110px;'>" + ClsManage.convert2Currency3(e.Item.DataItem("sumtotalarea").ToString).ToString + "</div></TD><TD align='center'><div style='width:65px;'>&nbsp;</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='center'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("sumsalearea").ToString).ToString + "</div></TD><TD align='center'><div style='width:65px;'>&nbsp;</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='center'><div style='width:110px'>" + ClsManage.convert2Currency3(ClsManage.convert2NoneZero(e.Item.DataItem("SumTotalRevenue"), e.Item.DataItem("sumsalearea")).ToString).ToString + "</div></TD><TD align='center'><div style='width:65px;'>&nbsp;</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='center'><div style='width:110px'></div></TD><TD align='center'><div style='width:65px;'>&nbsp;</div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg5'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumTotalRevenue").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTotalRevenue"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='aa1c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumRETAIL_TESPIncome").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRETAIL_TESPIncome"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='aa2c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOtherRevenue").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherRevenue"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumCostofGoodSold").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCostofGoodSold"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg5'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumGrossProfit").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGrossProfit"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumMarginAdjustments").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumMarginAdjustments"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b1c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumShipping").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumShipping"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b2c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumStockLossandObsolescence").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStockLossandObsolescence"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b3c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumInventoryAdjustment_stock").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumInventoryAdjustment_stock"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b4c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumInventoryAdjustment_damage").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumInventoryAdjustment_damage"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b5c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumStockLoss_Provision").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStockLoss_Provision"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b6c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumStockObsolescence_Provision").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStockObsolescence_Provision"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b7c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumGWP").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGWP"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b8c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumGWPs_Corporate").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGWPs_Corporate"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b9c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumGWPs_Transferred").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGWPs_Transferred"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b10c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumSellingCosts").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSellingCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b11c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumCreditcardscommission").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCreditcardscommission"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b12c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumLabellingMaterial").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumLabellingMaterial"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b13c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOtherIncome_COSHFunding").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherIncome_COSHFunding"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b14c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOtherIncomeSupplier").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherIncomeSupplier"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg5'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumAdjustedGrossMargin").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAdjustedGrossMargin"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumSupplyChainCosts").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSupplyChainCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg5'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumTotalStoreExpenses").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTotalStoreExpenses"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumStoreLabourCosts").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStoreLabourCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e1c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumGrossPay").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGrossPay"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e2c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumTemporaryStaffCosts").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTemporaryStaffCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e3c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumAllowance").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAllowance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e4c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOvertime").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOvertime"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e5c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumLicensefee").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumLicensefee"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e6c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumBonuses_Incentives").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumBonuses_Incentives"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e7c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumBootsBrandncentives").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumBootsBrandncentives"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e8c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumSuppliersIncentive").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSuppliersIncentive"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e9c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumProvidentFund").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumProvidentFund"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e10c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPensionCosts").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPensionCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e11c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumSocialSecurityFund").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSocialSecurityFund"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e12c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumUniforms").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumUniforms"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e13c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumEmployeeWelfare").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumEmployeeWelfare"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e14c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOtherBenefitsEmployee").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherBenefitsEmployee"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumStorePropertyCosts").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStorePropertyCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f1c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPropertyRental").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPropertyRental"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f2c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPropertyServices").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPropertyServices"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f3c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPropertyFacility").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPropertyFacility"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f4c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPropertytaxes").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPropertytaxes"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f5c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumFacialtaxes").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumFacialtaxes"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f6c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPropertyInsurance").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPropertyInsurance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f7c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumSignboard").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSignboard"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f8c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumDiscount_Rent_Services_Facility").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDiscount_Rent_Services_Facility"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f9c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumGPCommission").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGPCommission"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f10c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumAmortizationofLeaseRight").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAmortizationofLeaseRight"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumDepreciation").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciation"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='g1c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumDepreciationofShortLeaseBuilding").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciationofShortLeaseBuilding"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='g2c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumDepreciationofComputerHardware").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciationofComputerHardware"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='g3c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumDepreciationofFixturesFittings").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciationofFixturesFittings"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='g4c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumDepreciationofComputerSoftware").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciationofComputerSoftware"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='g5c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumDepreciationofOfficeEquipment").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciationofOfficeEquipment"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOtherStoreCosts").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherStoreCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h1c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumServiceChargesandOtherFees").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumServiceChargesandOtherFees"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h2c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumBankCharges").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumBankCharges"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h3c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumCashCollectionCharge").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCashCollectionCharge"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h4c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumCleaning").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCleaning"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h5c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumSecurityGuards").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSecurityGuards"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h6c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumCarriage").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCarriage"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h7c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency2(e.Item.DataItem("SumLicenceFees").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumLicenceFees"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h8c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOtherServicesCharge").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherServicesCharge"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h9c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOtherFees").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherFees"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h10c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumUtilities").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumUtilities"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h11c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumWater").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumWater"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h12c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumGas_Electric").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGas_Electric"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h13c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumAirCond_Addition").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAirCond_Addition"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h14c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumRepairandMaintenance").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRepairandMaintenance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h15c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumRMOther_Fix").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRMOther_Fix"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h16c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumRMOther_Unplan").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRMOther_Unplan"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h17c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumRMComputer_Fix").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRMComputer_Fix"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h18c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumRMComputer_Unplan").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRMComputer_Unplan"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h19c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumProfessionalFee").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumProfessionalFee"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h20c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumMarketingResearch").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumMarketingResearch"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h21c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOtherFee").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherFee"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h22c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumEquipment_MaterailandSupplies").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumEquipment_MaterailandSupplies"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h23c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPrintingandStationery").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPrintingandStationery"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h24c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumSuppliesExpenses").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSuppliesExpenses"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h25c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumEquipment").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumEquipment"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h26c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumShopfitting").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumShopfitting"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h27c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPackagingandOtherMaterial").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPackagingandOtherMaterial"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h28c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumBusinessTravelExpenses").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumBusinessTravelExpenses"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h29c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumCarParkingandOthers").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCarParkingandOthers"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h30c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumTravel").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTravel"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h31c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumAccomodation").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAccomodation"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h32c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumMealandEntertainment").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumMealandEntertainment"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h33c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumInsurance").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumInsurance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h34c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumAllRiskInsurance").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAllRiskInsurance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h35c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumHealthandLifeInsurance").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumHealthandLifeInsurance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h36c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPenaltyandTaxation").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPenaltyandTaxation"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h37c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumTaxation").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTaxation"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h38c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPenalty").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPenalty"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h39c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOtherRelatedStaffCost").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherRelatedStaffCost"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h40c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumStaffConferenceandTraining").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStaffConferenceandTraining"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h41c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumTraining").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTraining"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h42c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumCommunication").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCommunication"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h43c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumTelephoneCalls_Faxes").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTelephoneCalls_Faxes"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h44c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPostageandCourier").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPostageandCourier"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h45c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumOtherExpenses").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherExpenses"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h46c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumSample_Tester").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSample_Tester"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h47c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumPreopeningCosts").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPreopeningCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h48c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumLossonClaim").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumLossonClaim"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h49c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumCashOvertage_Shortagefromsales").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCashOvertage_Shortagefromsales"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h50c" + TbCk.Text + "'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumMiscellenousandOther").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumMiscellenousandOther"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg5'><TD align='right'><div style='width:110px'>" + ClsManage.convert2Currency3(e.Item.DataItem("SumStoreTradingProfit__Loss").ToString).ToString + "</div></TD><TD align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStoreTradingProfit__Loss"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "</TABLE>"
                Else
                    CType(e.Item.FindControl("label2"), Label).Text = "<TABLE cellspacing='0' cellpadding='0' class='tball'>" + _
                "<TR style='font-weight:bold;' class='kbg1'><TD align='center'><div style='width:80px'><strong>&nbsp;</strong></div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg1'><TD align='center'><div style='width:80px'><strong>%Growth</strong></div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='center'><div style='width:80px;'>&nbsp;</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='center'><div style='width:80px'>&nbsp;</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='center'><div style='width:80px'>&nbsp;</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='center'><div style='width:80px'>&nbsp;</div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg5'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumTotalRevenue").ToString).ToString + "</div></TD></TR>" + _
                "<TR id='aa1c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumRETAIL_TESPIncome").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRETAIL_TESPIncome"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='aa2c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOtherRevenue").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherRevenue"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumCostofGoodSold").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCostofGoodSold"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg5'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumGrossProfit").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGrossProfit"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumMarginAdjustments").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumMarginAdjustments"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b1c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumShipping").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumShipping"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b2c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumStockLossandObsolescence").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStockLossandObsolescence"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b3c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumInventoryAdjustment_stock").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumInventoryAdjustment_stock"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b4c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumInventoryAdjustment_damage").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumInventoryAdjustment_damage"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b5c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumStockLoss_Provision").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStockLoss_Provision"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b6c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumStockObsolescence_Provision").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStockObsolescence_Provision"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b7c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumGWP").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGWP"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b8c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumGWPs_Corporate").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGWPs_Corporate"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b9c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumGWPs_Transferred").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGWPs_Transferred"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b10c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumSellingCosts").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSellingCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b11c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumCreditcardscommission").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCreditcardscommission"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b12c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumLabellingMaterial").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumLabellingMaterial"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b13c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOtherIncome_COSHFunding").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherIncome_COSHFunding"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='b14c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOtherIncomeSupplier").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherIncomeSupplier"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg5'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumAdjustedGrossMargin").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAdjustedGrossMargin"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumSupplyChainCosts").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSupplyChainCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg5'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumTotalStoreExpenses").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTotalStoreExpenses"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumStoreLabourCosts").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStoreLabourCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e1c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumGrossPay").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGrossPay"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e2c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumTemporaryStaffCosts").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTemporaryStaffCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e3c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumAllowance").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAllowance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e4c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOvertime").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOvertime"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e5c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumLicensefee").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumLicensefee"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e6c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumBonuses_Incentives").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumBonuses_Incentives"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e7c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumBootsBrandncentives").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumBootsBrandncentives"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e8c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumSuppliersIncentive").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSuppliersIncentive"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e9c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumProvidentFund").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumProvidentFund"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e10c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPensionCosts").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPensionCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e11c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumSocialSecurityFund").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSocialSecurityFund"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e12c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumUniforms").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumUniforms"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e13c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumEmployeeWelfare").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumEmployeeWelfare"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='e14c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOtherBenefitsEmployee").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherBenefitsEmployee"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumStorePropertyCosts").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStorePropertyCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f1c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPropertyRental").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPropertyRental"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f2c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPropertyServices").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPropertyServices"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f3c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPropertyFacility").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPropertyFacility"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f4c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPropertytaxes").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPropertytaxes"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f5c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumFacialtaxes").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumFacialtaxes"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f6c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPropertyInsurance").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPropertyInsurance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f7c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumSignboard").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSignboard"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f8c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumDiscount_Rent_Services_Facility").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDiscount_Rent_Services_Facility"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f9c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumGPCommission").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGPCommission"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='f10c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumAmortizationofLeaseRight").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAmortizationofLeaseRight"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumDepreciation").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciation"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='g1c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumDepreciationofShortLeaseBuilding").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciationofShortLeaseBuilding"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='g2c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumDepreciationofComputerHardware").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciationofComputerHardware"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='g3c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumDepreciationofFixturesFittings").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciationofFixturesFittings"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='g4c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumDepreciationofComputerSoftware").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciationofComputerSoftware"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='g5c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumDepreciationofOfficeEquipment").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumDepreciationofOfficeEquipment"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOtherStoreCosts").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherStoreCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h1c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumServiceChargesandOtherFees").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumServiceChargesandOtherFees"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h2c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumBankCharges").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumBankCharges"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h3c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumCashCollectionCharge").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCashCollectionCharge"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h4c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumCleaning").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCleaning"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h5c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumSecurityGuards").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSecurityGuards"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h6c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumCarriage").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCarriage"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h7c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2Currency2(e.Item.DataItem("SumLicenceFees").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumLicenceFees"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h8c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOtherServicesCharge").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherServicesCharge"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h9c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOtherFees").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherFees"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h10c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumUtilities").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumUtilities"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h11c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumWater").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumWater"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h12c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumGas_Electric").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumGas_Electric"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h13c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumAirCond_Addition").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAirCond_Addition"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h14c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumRepairandMaintenance").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRepairandMaintenance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h15c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumRMOther_Fix").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRMOther_Fix"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h16c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumRMOther_Unplan").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRMOther_Unplan"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h17c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumRMComputer_Fix").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRMComputer_Fix"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h18c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumRMComputer_Unplan").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumRMComputer_Unplan"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h19c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumProfessionalFee").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumProfessionalFee"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h20c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumMarketingResearch").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumMarketingResearch"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h21c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOtherFee").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherFee"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h22c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumEquipment_MaterailandSupplies").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumEquipment_MaterailandSupplies"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h23c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPrintingandStationery").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPrintingandStationery"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h24c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumSuppliesExpenses").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSuppliesExpenses"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h25c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumEquipment").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumEquipment"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h26c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumShopfitting").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumShopfitting"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h27c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPackagingandOtherMaterial").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPackagingandOtherMaterial"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h28c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumBusinessTravelExpenses").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumBusinessTravelExpenses"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h29c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumCarParkingandOthers").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCarParkingandOthers"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h30c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumTravel").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTravel"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h31c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumAccomodation").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAccomodation"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h32c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumMealandEntertainment").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumMealandEntertainment"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h33c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumInsurance").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumInsurance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h34c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumAllRiskInsurance").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumAllRiskInsurance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h35c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumHealthandLifeInsurance").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumHealthandLifeInsurance"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h36c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPenaltyandTaxation").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPenaltyandTaxation"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h37c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumTaxation").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTaxation"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h38c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPenalty").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPenalty"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h39c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOtherRelatedStaffCost").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherRelatedStaffCost"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h40c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumStaffConferenceandTraining").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStaffConferenceandTraining"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h41c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumTraining").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTraining"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h42c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumCommunication").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCommunication"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h43c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumTelephoneCalls_Faxes").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumTelephoneCalls_Faxes"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h44c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPostageandCourier").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPostageandCourier"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h45c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumOtherExpenses").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumOtherExpenses"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h46c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumSample_Tester").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumSample_Tester"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h47c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumPreopeningCosts").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumPreopeningCosts"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h48c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumLossonClaim").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumLossonClaim"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h49c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumCashOvertage_Shortagefromsales").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumCashOvertage_Shortagefromsales"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR id='h50c" + TbCk.Text + "'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumMiscellenousandOther").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumMiscellenousandOther"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "<TR style='font-weight:bold;' class='kbg5'><TD align='right'><div style='width:80px'>" + ClsManage.convert2PercenLFLGrowth(e.Item.DataItem("SumStoreTradingProfit__Loss").ToString).ToString + "</div></TD><TD style='display:none' align='right'><div style='width:65px;'>" + ClsManage.convert2PercenNoneZero(e.Item.DataItem("SumStoreTradingProfit__Loss"), e.Item.DataItem("SumTotalRevenue")).ToString + "%</div></TD></TR>" + _
                "</TABLE>"
                End If

            Else
                CType(e.Item.FindControl("label2"), Label).Text = ""
            End If
        End If
    End Sub

End Class
